// <auto-generated />
using Labb4_Advanced_API.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Labb4_Advanced_API.Migrations
{
    [DbContext(typeof(SomeDbContext))]
    partial class SomeDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Labb4_Advanced_API.Models.Interests", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Interests");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Description = "A MMO game",
                            Title = "WoW"
                        },
                        new
                        {
                            ID = 2,
                            Description = "coding",
                            Title = "Coding"
                        },
                        new
                        {
                            ID = 3,
                            Description = "fishing",
                            Title = "Fishing"
                        },
                        new
                        {
                            ID = 4,
                            Description = "A sport",
                            Title = "Football"
                        });
                });

            modelBuilder.Entity("Labb4_Advanced_API.Models.LinksIntrests", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("InterestsId")
                        .HasColumnType("int");

                    b.Property<string>("Link")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("InterestsId");

                    b.HasIndex("PersonId");

                    b.ToTable("LinksIntrests");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            InterestsId = 1,
                            Link = "www.wowhead.com",
                            PersonId = 1
                        },
                        new
                        {
                            ID = 2,
                            InterestsId = 1,
                            Link = "www.worldofwarcraft.blizzardcom",
                            PersonId = 1
                        },
                        new
                        {
                            ID = 3,
                            InterestsId = 2,
                            Link = "www.learn.microsoft.com",
                            PersonId = 1
                        },
                        new
                        {
                            ID = 4,
                            InterestsId = 3,
                            Link = "www.fiske.se",
                            PersonId = 1
                        },
                        new
                        {
                            ID = 5,
                            InterestsId = 2,
                            Link = "www.Github.com",
                            PersonId = 2
                        },
                        new
                        {
                            ID = 6,
                            InterestsId = 2,
                            Link = "www.github.com",
                            PersonId = 3
                        },
                        new
                        {
                            ID = 7,
                            InterestsId = 4,
                            Link = "www.wikipedia/foorball.com",
                            PersonId = 2
                        });
                });

            modelBuilder.Entity("Labb4_Advanced_API.Models.Person", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Persons");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Name = "Emil",
                            PhoneNumber = "123456789"
                        },
                        new
                        {
                            ID = 2,
                            Name = "Isak",
                            PhoneNumber = "987654321"
                        },
                        new
                        {
                            ID = 3,
                            Name = "Lucas",
                            PhoneNumber = "000000000"
                        });
                });

            modelBuilder.Entity("Labb4_Advanced_API.Models.LinksIntrests", b =>
                {
                    b.HasOne("Labb4_Advanced_API.Models.Interests", "Interests")
                        .WithMany("LinksPerson")
                        .HasForeignKey("InterestsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Labb4_Advanced_API.Models.Person", "Person")
                        .WithMany("LinksIntrests")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Interests");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Labb4_Advanced_API.Models.Interests", b =>
                {
                    b.Navigation("LinksPerson");
                });

            modelBuilder.Entity("Labb4_Advanced_API.Models.Person", b =>
                {
                    b.Navigation("LinksIntrests");
                });
#pragma warning restore 612, 618
        }
    }
}
